---
# From https://google.github.io/osv-scanner/github-action/
name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: "30 2 * * *"
  # Change "main" to your default branch if you use a different name
  push:
    branches: [main]

permissions:
  # Required to upload SARIF file to CodeQL.
  # See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@2a387edfbe02a11d856b89172f6e978100177eb4" # v2.3.2
